### ISSUE TITLE
Feature:  Add "Live Now" on Navigation Bar if the show is live

### ISSUE THREAD

**Issue by javierxio** [jwkent/AudioWebApp#118]
Something like this would be nice when the show is live. Thanks.

![image](https://github.com/jwkent/AudioWebApp/assets/63758477/4d9b858e-57ae-43db-ba47-5323c2a182b2)

**Comment by jwkent** [comment]
Thank you for the suggestion. On a mobile device, which most of the users of this app are, the menu is usually closed which would not provide any alert that the radio show is now live.  I would agree with your suggestion if the majority of users were desktop users, but they are not so I am closing this issue as too much effort for limited value.
