### ISSUE TITLE
Feature:  Highlight the background for selections

### ISSUE THREAD

**Issue by javierxio** [jwkent/AudioWebApp#119]
Is it possible to highlight selections? This will make it easier to visually see on which item in the list I am on. Thanks.
Current:

![image](https://github.com/jwkent/AudioWebApp/assets/63758477/83d55baa-fe66-4f76-bff1-19003a0ac939)

Future (similar):

![image](https://github.com/jwkent/AudioWebApp/assets/63758477/b730f10f-5b4a-4e4a-b309-f6a493b7b4a4)

**Comment by jwkent** [comment]
Hi @javierxio,

If you would like to take on this issue and submit a MR, I will accept it. I don't think we will work on it as it has limited value since the user can see what is being played using the label above the player control.
