### ISSUE TITLE
Create a link for recommend audio / ebooks by the narrow path

### ISSUE THREAD

**Issue by jwkent** [jwkent/AudioWebApp#120]
Can we create a "Recommended audio and ebooks" link that takes the user to the following site?

https://www.everand.com/lists/26277194/The-narrow-path

I have created this list from Steve.

**Comment by jwkent** [comment]
I think extras.

**Comment by benjkent** [comment]
Ok. I have a really smashing idea. Need some time to get it right. Pretty sure it will work.
