### ISSUE TITLE
iOS: System playback controls fail to un-pause tracks when app is not open

### ISSUE THREAD

**Issue by JacksonKearl** [jwkent/AudioWebApp#124]
1. Start playback
2. Turn off phone
3. Open lock screen, pause using the "payback widget"
4. Now, "Play"
5. Bug: Track does not play

**Comment by JacksonKearl** [comment]
Hm, this only reproduces when the app is installed as a PWA. Seems to be a bug in the iOS PWA implementation – I cannot find any mention of this online.

**Comment by jwkent** [comment]
I have noticed some strangeness around this topic, but I'm not sure how to address it. It appears to be at the iOS level and not much the PWA has control over. 

I will leave this issue open for a few weeks if you would like to investigate a possible fix, that would be most welcome.

**Comment by JacksonKearl** [comment]
I wonder if it's an issue of the DOM being deallocated, and whether using the JS [Web Audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API) might help.

**Comment by JacksonKearl** [comment]
@jwkent I was able to produce a fix, though it is a bit of a hack. However it's applied only when absolutely needed, and using the application on iOS PWA without it is very cumbersome.
