### ISSUE TITLE
Add a second youtube link since there are two youtube channels.

### ISSUE THREAD

**Issue by jwkent** [jwkent/AudioWebApp#26]
[TNP](https://www.youtube.com/c/TheNarrowPath/videos)
[Steve Gregg](https://www.youtube.com/c/SteveGreggVideos/videos)

We should go through all these resources and see if any should be included in the extras section.

The Narrow Path.com
[thenarrowpath.com](https://www.youtube.com/redirect?event=channel_description&redir_token=QUFFLUhqbXpyU3R3TVhUWlAtRDlDUTVPR2VncWVzSFBVQXxBQ3Jtc0tubm04WDdDeFZCb3pLVW9KNGpfS2dZUzFPSWxvNFk3OWxsQnpHNGp5UDlCQWpDM0ZLdjVsclNzalpHc3RCOF9hckdwcHpsUUhwckIxTzhZNzcyVmJfSEtqTW92NXlBcDlsTnNEWXl4LTNLSUJLUUNiNA&q=http%3A%2F%2FTheNarrowPath.Com)

The Narrow Path YT
[youtube.com/@TheNarrowPath](https://www.youtube.com/@TheNarrowPath)

Facebook
[facebook.com/groups/stevegreggtnp](https://www.youtube.com/redirect?event=channel_description&redir_token=QUFFLUhqbEZUOE1lc1dZX1laMHc3Sk92RjFMamJvWElZQXxBQ3Jtc0tudU1kQV94Q3ZZaWd6THV0cmlBSDU0SVZTRXJ6cUZ0cjlEdEctZ0NNa1NlUUdnVnBTaGF2TGFrSzBiNFVJS1ZTVUZrU2VZcWFTbl91SEVwVFFOeldPWURQcUZPc3dPVWtMNmpXT1dhZlRSd3ljS0hKaw&q=https%3A%2F%2Fwww.facebook.com%2Fgroups%2Fstevegreggtnp)

Steve's Radio Calls & Notes
[matthew713.com](https://www.youtube.com/redirect?event=channel_description&redir_token=QUFFLUhqbGV5bndtZWVaeDZSaVlJanU4aTBNRDFFNEpiQXxBQ3Jtc0tuQ0VzZm51alBMWDl0a2wwMGRpRUxmei1sTmQwUjhyMy1WRFRXNVFUekVCR0ZSM1BBbVBEeG15X2Rrak5Pbmo0cDNkdkU4X09lNEpPZkxEaVZjNnFNanJsNG9JVWJKLVVJVW9Ud0d3V0pxeWp5NV9FOA&q=http%3A%2F%2Fwww.Matthew713.com)

The Narrow Path Broadcast
[youtube.com/channel/UCN5fklHp2GkkaQMoGpueckQ](https://www.youtube.com/channel/UCN5fklHp2GkkaQMoGpueckQ)

Transcribed S. Gregg Lectures
[opentheo.org/steve-gregg](https://www.youtube.com/redirect?event=channel_description&redir_token=QUFFLUhqbEZNVjliYWdEbzF5UWI0Qjg2bEZCTW83bHEyd3xBQ3Jtc0treWQ5QWNWN05GdXpDdktDRTNFTnZpaS1GXzY4ajI0Y2pBVHBDN0tNel9pR0EwNnV1OFUtZE5ScjZmVENGSGlLQ243U2hTSkU1RV9WbnRWVGRjb2dSRWJMdFY1ZXBlMGMzOXRUZTE5WEw2d1N2aXFsbw&q=https%3A%2F%2Fopentheo.org%2Fsteve-gregg)

Blogger
[greatcommissionschool.blogspot.com](https://www.youtube.com/redirect?event=channel_description&redir_token=QUFFLUhqbHJWRmpLTDhicVY2RFR3WG9PQXpHNUljOHI3UXxBQ3Jtc0tseTFwNEFoTGx5N2t2UFFRcFdZbGVtNVVPckdaajJIN2JtU3hicDRkZGhDby0yLVpGSzNFaktJWGJTdGVyNWYwcV9LQlA1TlhHQ1FIU2luMllxR1lJRlNNbWE1a1hxWFhuZE15aG9jNHFLZ3N2Nk5RTQ&q=http%3A%2F%2Fgreatcommissionschool.blogspot.com)

SteveGreggVideos Facebook
[facebook.com/profile.php?id=61555659462538](https://www.youtube.com/redirect?event=channel_description&redir_token=QUFFLUhqbVZFYzFtSmhJdFNJakRmTnluTktQUlN4RUoxd3xBQ3Jtc0tsbXg1dzMzLTR4b0VjNURoRHJTRlRsdzJRMExrUml4cjVscnJtaVhYNXR6dVBjZHBKcE96ZU5XLVd3X21MdS16cXczS1NLWEZGV1A2aWo1Zk9TMHV2R2NnZkdNVnl0V1M4WXBuNFVnZkc2TV90emdrQQ&q=https%3A%2F%2Fwww.facebook.com%2Fprofile.php%3Fid%3D61555659462538)

The Narrow Path Podcast
[tnp.theeggbeater.net](https://www.youtube.com/redirect?event=channel_description&redir_token=QUFFLUhqbEw0NGU3SE41SmVnVWdOWUxQRG00a25uVmhtd3xBQ3Jtc0ttdG1xUWJzVmJKdURoZWFobDh0SVJYeGRwbm1OSGdwendzRGFwNjVjS3NJZGFvaEcwTGY2aDI3cjVjYWlDeHk0VmlqdXVXTFFXWjVjMEQ4RUx2ZE5vM2k5azdsRmZsYzNXMko1eXJrZVItLWlBdmNDZw&q=http%3A%2F%2Ftnp.theeggbeater.net%2F)

S. Gregg @ theos.org
[theos.org/media](https://www.youtube.com/redirect?event=channel_description&redir_token=QUFFLUhqbTBBRldEZXEzaVpkSU9nRzNYSDA5bTlVUGl4UXxBQ3Jtc0tsUGJ0empzbkMzRGlGclVTT3g3ak5nWi1zbVFZakVjU2tMcGhVOFVKc3VnRlI1VTNMTHg2c2F6aUgtQjBhZ2xuM1hSbEZIUWN3QUw2VkxmcXFyNlBsX3pkSnpVOTlmRHNnLWI5ZWxRZGhuZFhQX2h6dw&q=http%3A%2F%2Fwww.theos.org%2Fmedia%2F)

The Narrow Path Bible Forum
[theos.org/forum](https://www.youtube.com/redirect?event=channel_description&redir_token=QUFFLUhqbWZVUmYtT0MwUmgyMGc0UmdEVm9wTGtyTU0yd3xBQ3Jtc0ttLTBEeURZTWhxcm45c2RXNmhtVm9jbGQzSl9wa3FNNVpHOU1vZ2h0TkJkTDlYN1FmMjdJaVRaMkQ4RHp3Z1k1a1JzN0k1aE0tclhfTks5VE5qQnhaWGE4M01CTU44WEs3UGEwLU5FYkhnYTNpVGpMRQ&q=http%3A%2F%2Fwww.theos.org%2Fforum%2F)

The Road to Find Out archives
[theos.org/media/section/27](https://www.youtube.com/redirect?event=channel_description&redir_token=QUFFLUhqa0xDeDVWZEc5Ukh5Nzd1YVVtQjVsM0psSmpUZ3xBQ3Jtc0tub1YwOGFZSzVfYUs1WnFhdnBWR3pTdWZqd0JSMXBCM0FfZ2xQSi1SUHZOMVlndnB4SXB2U1hqb2t3NmRpbDVFMjBiX2lVWW93cFdrQVJlVGxUUjl1aUs1WmowZ0dpVUpsejNoSjZtN2k2elNMcHlPbw&q=http%3A%2F%2Ftheos.org%2Fmedia%2Fsection%2F27%2F)

**Comment by benjkent** [comment]
Handled in #27 add a contact us section
