### ISSUE TITLE
Announcements should be on an announcements menu item.

### ISSUE THREAD

**Issue by jwkent** [jwkent/AudioWebApp#33]
The announcements should be put on a new "Announcements" menu item not the main screen. I would put the branding back on the home screen. We should probably put a paragraph describing why this web app exists and why it exists.

I would put all of the info about each particular announcement in the announcement card and remove the "Learn More" button. It doesn't add enough value to takes the user away from the app.

![Image](https://github.com/jwkent/AudioWebApp/assets/6319674/84d20fd1-db5b-4cb5-8a01-68354d3c07c9)

**Comment by benjkent** [comment]
Done and Merged with main
