### ISSUE TITLE
Minor UI improvements feed back from John Marr

### ISSUE THREAD

**Issue by jwkent** [jwkent/AudioWebApp#48]
I asked John Marr to review the web app:

- Group debates together in accordion style, they are just one after the other areas as it's hard to tell which is which.
- Add some kind of button at the bottom of home screen like "learn more", "explore" that opens the menu tray.
- Possibly a faint lesson count in the accordion headers so you know how many are in each.

**Comment by benjkent** [comment]
Statement of purpose. Objective of this site.
Favorite your audio files.
Remembers where your listen point was.
All of the audio content from the narrow path.
Radio

**Comment by benjkent** [comment]
`<MudListItem>
    <ChildContent>
<MudStack Row="true">
<a>@topic.Name</a>
<a>@topic.Messages.Count()</a>
</MudStack>
</ChildContent>
    <NestedList>`

Add numerical count to MudListItem...

**Comment by benjkent** [comment]
Breaking these task up.

**Comment by benjkent** [comment]
Closing as transferred to separate issues.
