### ISSUE TITLE
Add installation instructions for Android in "How To"

### ISSUE THREAD

**Issue by javierxio** [jwkent/AudioWebApp#72]
1. Press the three dots on the top right-hand corner in the browser
2. Press "Install app" in the menu options
3. Press "Install" to install app
4. Press "Add to home screen" 

Pictures attached. Please annotate as needed. 
![Screenshot_20240313-172323](https://github.com/jwkent/AudioWebApp/assets/63758477/a661beb8-6bb0-4b33-b1d1-b1e33c210d52)
![Screenshot_20240313-172339](https://github.com/jwkent/AudioWebApp/assets/63758477/d7999c50-ae34-4987-b10c-dee9f7d95d73)
![Screenshot_20240313-172347](https://github.com/jwkent/AudioWebApp/assets/63758477/4c4243e1-40f7-4775-a4ba-9d5e195e63a8)
![Screenshot_20240313-172409](https://github.com/jwkent/AudioWebApp/assets/63758477/2408c7e4-6c94-41c0-a0f0-ca190523de03)

**Comment by benjkent** [comment]
Working on it.
