### ISSUE TITLE
Text almost cut off at the right edge of screen

### ISSUE THREAD

**Issue by javierxio** [jwkent/AudioWebApp#75]
The text is right against the right edge of the screen. Would be good to align it more centered.

![image](https://github.com/jwkent/AudioWebApp/assets/63758477/4d535d73-d8cd-43fc-88f0-008b1cb2c8a0)
![image](https://github.com/jwkent/AudioWebApp/assets/63758477/78fc7b34-b2fc-43a7-9637-6b125bdce729)

**Comment by benjkent** [comment]
Added 20px to the padding-right just under the default 32px on left. Emulators don't show any problems. So keep an eye on this when it Change goes to production. Thx.
