### ISSUE TITLE
Code changes not taking effect

### ISSUE THREAD

**Issue by javierxio** [jwkent/AudioWebApp#78]
Hello. I am on Android 13. I installed the app about a week ago and it seems a few tickets of mine were addressed however I do not see the changes taking effect in the app. My app version shows as 1.0.3.

For example, in Extras, I do not see Matthew713 but it seems a code change was made here:  https://github.com/jwkent/AudioWebApp/pull/71

Also, I still have issue with text cut off:  https://github.com/jwkent/AudioWebApp/pull/77

And audio controls are still cut off:  https://github.com/jwkent/AudioWebApp/pull/74

So I just want to know why I am not seeing the changes on my side. Thanks.

![Screenshot_20240315-104952](https://github.com/jwkent/AudioWebApp/assets/63758477/00bdfc25-17cd-4afd-a726-572d047e8f03)

**Comment by benjkent** [comment]
Your issues were very immensely helpful and I hope that the changes/fixes will be reflected soon. We had a few other improvements that needed to be put into production asap. So, please stay tuned. 
![M713](https://github.com/jwkent/AudioWebApp/assets/68797909/8c9b171a-c574-4591-a541-833f72434018)
![padding-player](https://github.com/jwkent/AudioWebApp/assets/68797909/33c1d2fe-2221-4c72-9081-569fd19774ea)
There may need to be even more fine tuning. Thanks again.

**Comment by javierxio** [comment]
I see the new update in version 1.0.4. Thanks.
