### ISSUE TITLE
Show message or indicator when the show is Live (on the radio page)

### ISSUE THREAD

**Issue by javierxio** [jwkent/AudioWebApp#96]
Hello. I believe that the narrow path website shows an indicator when the radio show is Live (in other words, weekdays 2-3PM). I believe it shows a green indicator during this time. When it is outside of this time window, the indicator shows red.

Could be neat to include this kind of feature. Thanks.

Currently, there is a Green phone dialer indicator always showing on the Radio page:

![Screenshot_20240322-161913](https://github.com/jwkent/AudioWebApp/assets/63758477/c5f78b4b-204a-4276-9273-7ad404b5e88a)

**Comment by benjkent** [comment]
No promises but I think this could be accomplished with this:
![image](https://github.com/jwkent/AudioWebApp/assets/68797909/95671b5d-57b6-4dbd-b9e9-195fcc3eb6a5)
Colors and shapes will be better.

**Comment by benjkent** [comment]
Or better top center?
![image](https://github.com/jwkent/AudioWebApp/assets/68797909/de133ef6-4af2-4e9c-97f7-0784d73b5a86)

**Comment by javierxio** [comment]
@benjkent Looks good. You can even add a message like "Live Now!" or similar.

The first image looks better. I would even suggest to change the dialer color to red when not live (or disable).

**Comment by benjkent** [comment]
Thanks we discussed the disable button idea and decided that any potential time bug for non US listeners or stopping people from using a button was too big a risk. So perhaps we can just see how the "live" button appearance change will be of value. And if there was a bug it would not ruin anyone's experience.

**Comment by benjkent** [comment]
After writing some of the code I see a potential failure that hopefully will not be the norm, but it is a great idea and will make the radio page stand out. Will have it done in a couple of days. As I need to do some work another aspect also.

**Comment by benjkent** [comment]
Here is the feature in action. 
![image](https://github.com/jwkent/AudioWebApp/assets/68797909/0edb3083-a7fe-409a-ae65-13138d8c5541)

**Comment by javierxio** [comment]
Thanks @benjkent . The live button looks a bit cluttered when the green dot is added. Is it able to place it better in addition to possibly making the boxes larger?

**Comment by javierxio** [comment]
This is from TNP website while the show is live:

![image](https://github.com/jwkent/AudioWebApp/assets/63758477/d3dc5812-2dda-4708-9cf9-28c11fabd414)
![image](https://github.com/jwkent/AudioWebApp/assets/63758477/2425167b-ea99-4183-8612-1a31dc3c74ae)

**Comment by benjkent** [comment]
Thanks for the upvote. Your point is well taken, I tried the top and it was funny looking. Hence the bottom center. I added some room so it's less smushed. 
![image](https://github.com/jwkent/AudioWebApp/assets/68797909/58b9c8e4-d953-4b49-a3a9-d4ef7960a072)
The text change from RADIO to LIVE (with the dot) can help people with differing color vision abilities decern the importance as well.

**Comment by javierxio** [comment]
@benjkent can you also change the casing on BroadCast to Broadcast? Thanks.
