### ISSUE TITLE
Bug:  Strange string appears on homepage

### ISSUE THREAD

**Issue by javierxio** [jwkent/AudioWebApp#98]
I am seeing this string on the top-left of the home page. I don't know if it is a bitcoin address or some other hash: IwAR0BYPSiLCypGRDp1Z6pZTtLdr_6SBvUkt4bu1T2EvsSihuPp08MMjPU0U0

![Screenshot_20240323-161421](https://github.com/jwkent/AudioWebApp/assets/63758477/424c43dd-ba82-417f-a4e7-d0a7dc0f7729)

**Comment by benjkent** [comment]
Check your version against the current version in source control. 1.0.5  That is very strange??? Then try reset reload, type techniques to see if it persists.

**Comment by benjkent** [comment]
No issues on any devices I have running. LMK

**Comment by jwkent** [comment]
Could you please describe the steps you did to help us reproduce this issue. Thank you.

**Comment by javierxio** [comment]
Not able to reproduce. Seems it was only that one time and I have not seen it since.
